parameters:
    app.base_url_api: '%env(BASE_URL_API)%'

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind: # Identifica qualquer construtor com a vari√°vel e injeta automaticamente
            $baseUrlApi: '%app.base_url_api%'

    App\:
        resource: '../src/'

    App\EventListener\ApiExceptionListener:
        tags: 
            - { name: kernel.event_listener, event: kernel.exception }
